name: code quality

on:
  #workflow_call:
  push:

jobs:

  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]

    steps:

      - name: code checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: install eslint + parser
        run: npm install --save-dev eslint@9 @eslint/js@9 @babel/eslint-parser @babel/preset-react --legacy-peer-deps

      - name: install dependencies
        run: |
          npm install
          npm audit fix
          npm run
        working-directory: ${{ matrix.folder }}

      - name: run lint
        run: npm run lint actions/setup-node@v6
